// Generated by CoffeeScript 1.3.3
var LoopView,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  __slice = [].slice;

LoopView = (function(_super) {

  __extends(LoopView, _super);

  function LoopView(options) {
    var modoptions;
    if (options == null) {
      options = {};
    }
    modoptions = _.extend({}, this.defaults, options);
    LoopView.__super__.constructor.call(this, modoptions);
    this.gather();
    this.attach();
  }

  LoopView.prototype.defaults = {
    loopTemplate: $('#loop-detail-template').html(),
    menuTemplate: $('#loop-menu-template').html()
  };

  LoopView.prototype.el = '#loop';

  LoopView.prototype.events = {};

  LoopView.prototype.gather = function() {
    this.templates = {
      loop: Hogan.compile(this.options.loopTemplate),
      menu: Hogan.compile(this.options.menuTemplate)
    };
    this.element = this.$el;
    return this.els = {
      "delete": $('#delete'),
      menu: $('#loop-menu')
    };
  };

  LoopView.prototype.attach = function() {
    var run, selector, _ref,
      _this = this;
    _.bindAll(this, 'edit', 'mod');
    this.clickEvent = window.mobile === true ? "tap" : "click";
    this.clickEvents = {
      '#amount': {
        method: "edit",
        args: ["amount"]
      },
      '#subtract': {
        method: "mod",
        args: ["amount", -1]
      },
      '#add': {
        method: "mod",
        args: ["amount", 1]
      }
    };
    _ref = this.clickEvents;
    for (selector in _ref) {
      run = _ref[selector];
      this.element.on(this.clickEvent, selector, _.bind.apply(_, [this[run.method], this].concat(__slice.call(run.args))));
    }
    this.els["delete"].on('click', _.bind(this.menu, this, 'delete'));
    return $(document).on(this.clickEvent, "body.menu", function(e) {
      var $body, el, id;
      el = $(e.target);
      id = el.attr('id');
      $body = $(document.body);
      if (el.parent().attr('id') !== 'menu-buttons' && id !== 'delete') {
        $body.removeClass(_this.menuClass);
      }
      if (id === "save") {
        return _this[el.html().toLowerCase()]();
      } else if (id === "cancel") {
        return $body.removeClass(_this.menuClass);
      }
    });
  };

  LoopView.prototype.edit = function(prop) {};

  LoopView.prototype.mod = function(prop, amount) {
    var val;
    val = (this.model.get(prop) || 0) + amount;
    this.els[prop].html(val);
    return this.model.set(prop, val);
  };

  LoopView.prototype.menu = function(operation) {
    var html;
    this.menuClass = "menu menu-" + operation;
    html = this.templates.menu.render(this.helpers[operation]);
    this.els.menu.html(html);
    return $(document.body).addClass(this.menuClass);
  };

  LoopView.prototype["delete"] = function() {
    var $parent, els, properRemove;
    $parent = $("#" + (this.model.get('id')));
    properRemove = function(e) {
      var $this;
      $this = $(this);
      if ($this.is('li')) {
        $this.remove();
      } else {
        $this.html('');
      }
      return $this.off(e.type, properRemove);
    };
    els = $parent.add(this.element);
    els.on({
      'webkitTransitionEnd': properRemove,
      'transitionEnd': properRemove
    });
    loopsView.view({
      target: $parent
    });
    els.addClass('delete');
    return this.collection.remove(this.model.get('id'));
  };

  LoopView.prototype.render = function(template, model) {
    if (template == null) {
      template = this.templates.loop;
    }
    this.model = model;
    if (!(this.helpers != null)) {
      this.helpers = this.defineHelpers();
    }
    this.latestTemplateData = _.extend({}, this.helpers, this.model);
    this.element.html(template.render(this.latestTemplateData));
    this.postRender();
    return this.trigger('render', this, model);
  };

  LoopView.prototype.openMenu = function() {};

  LoopView.prototype.postRender = function() {
    return _.extend(this.els, {
      amount: this.element.find('#amount')
    });
  };

  LoopView.prototype.restore = function(model) {
    this.model = model;
    return this.trigger('restore', this.model);
  };

  LoopView.prototype.defineHelpers = function() {
    var thiz;
    thiz = this;
    return {
      amount: function() {
        var val;
        val = this.get('amount') || 0;
        if (val !== 0) {
          thiz.openMenu();
        }
        return val;
      },
      "delete": {
        cancel: "Cancel",
        save: "Delete"
      }
    };
  };

  return LoopView;

})(Backbone.View);
