// Generated by CoffeeScript 1.3.3
var LoopsView,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

LoopsView = (function(_super) {

  __extends(LoopsView, _super);

  function LoopsView(options) {
    var attrs, _ref;
    if (options == null) {
      options = {};
    }
    attrs = _.extend({}, this.defaults, options);
    if (!(attrs.collection != null)) {
      throw new Error('No collection given');
    }
    this.preProcess();
    LoopsView.__super__.constructor.call(this, attrs);
    _ref = this.options, this.collection = _ref.collection, this.subView = _ref.subView;
    this.gather();
    this.attach();
    this.helpers = this.defineHelpers();
  }

  LoopsView.prototype.preProcess = function() {
    var addClicks,
      _this = this;
    return addClicks = (function() {
      var method, selector, _ref;
      _this.clickEvent = window.mobile === true ? "tap" : "click";
      _this.clickEvents = {
        '.loop-item': 'view',
        'label': 'edit'
      };
      _ref = _this.clickEvents;
      for (selector in _ref) {
        method = _ref[selector];
        _this.events["" + _this.clickEvent + " " + selector] = method;
      }
      return _this.events['keydown .new-loop'] = function(e) {
        if (e.keyCode === 13) {
          e.preventDefault();
          return $(e.target).blur();
        } else if (e.keyCode === 27) {
          e.preventDefault();
          return $(e.target).attr('value', '').blur();
        }
      };
    })();
  };

  LoopsView.prototype.gather = function() {
    this.element = this.$el;
    this.els = {
      "new": $('#create'),
      portability: $('#data-buttons'),
      additional: $('#additional'),
      container: $('.container')
    };
    return this.templates = {
      loops: $("#" + this.options.templateId).html(),
      "new": $("#" + this.options.newLoopTemplateId).html()
    };
  };

  LoopsView.prototype.attach = function() {
    var _this = this;
    _.bindAll(this, 'edit', 'view', 'delete');
    this.element.on('blur', 'input.new', function(e) {
      return _this.save.call(_this, e.target);
    });
    this.els["new"].on(this.clickEvent, function() {
      var newLoop;
      newLoop = _this.$('.new-loop input');
      if (newLoop.length > 0) {
        newLoop.blur();
      }
      return _this.collection.add([new Loop({})]);
    });
    this.collection.on('add', function(model) {
      return _this["new"](model);
    });
    this.collection.on('reset', function() {
      return _this.render();
    });
    this.collection.on('remove', function(model) {
      return _this["delete"](model);
    });
    return this.subView.on('restore', _.bind(this.restore, this));
  };

  LoopsView.prototype.el = '#loops';

  LoopsView.prototype.events = {};

  LoopsView.prototype.defaults = {
    templateId: 'loop-template',
    newLoopTemplateId: 'loop-new-template'
  };

  LoopsView.prototype["new"] = function(model, replace) {
    var data, html;
    data = _.extend({}, this.helpers, model.toJSON());
    html = Mustache.render(this.templates["new"], data);
    if (replace) {
      replace.outerHTML = html;
    } else {
      this.element.prepend(html);
    }
    return this.$('.new').focus();
  };

  LoopsView.prototype.save = function(el, model) {
    var $parent, value;
    $parent = $(el).parent();
    if (!(model != null)) {
      model = this.collection.get($parent.attr('id'));
    }
    if (el.value === '' && model.get('label') === void 0) {
      return this.collection.remove(model);
    } else if (el.value === '') {
      value = model.get('label');
    } else {
      value = el.value;
    }
    model.set('label', value);
    this.collection.sync('update', model.attributes);
    return this.render();
  };

  LoopsView.prototype.view = function(e) {
    var $newLoop, el, newLoop,
      _this = this;
    el = $(e.target);
    if (!el.is('li')) {
      return;
    }
    $newLoop = this.element.find('.new-loop');
    if ($newLoop[0] != null) {
      newLoop = this.collection.get($newLoop.attr('id'));
      this.save($newLoop.find('input')[0], newLoop);
      el = $("#" + e.target.id);
      e.target = el[0];
    }
    if (scrollY !== 0) {
      if (window.mobile === true) {
        window.scrollTo(0, 0);
      } else {
        $.scroll(0);
      }
    }
    if (this.slideList(e.target) === true) {
      this.subView.render(null, this.collection.get(e.target.id));
      return setTimeout(function() {
        return $(document.body).attr('class', 'show viewing ' + _this.subView.menuClass);
      }, 1);
    } else {
      this.subView.menuClass = '';
      $(document.body).attr('class', 'show');
      this.trigger('render', this);
      return this.postRender();
    }
  };

  LoopsView.prototype.slideList = function(element) {
    var $el, $prev, elOffset, next, offset, padding, prev, top, transform;
    $el = $(element);
    prev = element.previousElementSibling;
    next = element.nextElementSibling;
    transform = browser.flag + "transform";
    offset = this.element.offset().top;
    elOffset = $el.offset().top - offset;
    if ($el.hasClass('active')) {
      this.element.css(transform, 'translate3d(0,0,0)').css('height', '');
      $el.removeClass('active').css(transform, 'translate3d(0,-' + elOffset + 'px,0)');
      $el.siblings().css(transform, 'translate3d(0,0,0)');
      this.els.additional.removeClass('slide');
      return false;
    } else {
      padding = window.mobile === true ? 0 : 30;
      this.element.css(transform, 'translate3d(0,-' + offset + 'px,0)').css('height', window.ogHeight - offset - padding);
      $el.addClass('active').css(transform, 'translate3d(0,-' + elOffset + 'px,0)');
      while (prev != null) {
        $prev = $(prev);
        top = $prev.offset().top + $prev.height();
        $prev.css(transform, 'translate3d(0,-' + top + 'px,0)');
        prev = prev.previousElementSibling;
      }
      while (next != null) {
        $(next).addClass('next').css(transform, "translate3d(0," + window.ogHeight + "px,0)");
        next = next.nextElementSibling;
      }
      this.els.additional.addClass('slide');
      return true;
    }
  };

  LoopsView.prototype.edit = function(e) {
    var el, model;
    el = $(e.target).parent();
    if (el.hasClass('active')) {
      return this.view({
        target: el[0]
      });
    }
    model = this.collection.get(el.attr('id'));
    return this["new"](model, el[0]);
  };

  LoopsView.prototype["delete"] = function(model) {
    var id;
    id = model.get('id');
    return $("#" + id).remove();
  };

  LoopsView.prototype.render = function(template, data) {
    var html, templateData;
    if (template == null) {
      template = this.templates.loops;
    }
    data = data || _.sortBy(this.collection.toJSON(), function(i) {
      return -1 * this.get(i.id).cid.slice(1);
    }, this.collection);
    templateData = _.extend({}, this.helpers, {
      loops: data
    });
    this.latestTemplateData = templateData;
    html = Mustache.render(template, templateData);
    this.element.html(html);
    this.postRender();
    return this;
  };

  LoopsView.prototype.postRender = function() {
    var height;
    this.els.loops = this.element.find('.loop-item');
    if (this.collection.models.length > 0) {
      this.els.portability.addClass('show');
    } else {
      this.els.portability.removeClass('show');
    }
    height = this.els.loops.length * this.els.loops.height();
    if (window.mobile === true && height >= 370) {
      return this.els.container.css({
        height: height + 75,
        'max-height': height + 75
      });
    }
  };

  LoopsView.prototype.restore = function(model) {
    this.render();
    if (model) {
      return this.view({
        target: $("#" + model.id)[0]
      });
    }
  };

  LoopsView.prototype.defineHelpers = function() {
    var thiz;
    thiz = this;
    return {
      placeholder: function() {
        return this.label || 'Loop Name';
      }
    };
  };

  return LoopsView;

})(Backbone.View);
