// Generated by CoffeeScript 1.3.3
var music;

music = ['http://rd.io/x/QH6PK0JQ85k', 'http://rd.io/x/QH6PK0JOb-w', 'http://rd.io/x/QH6PK0JOb5M', 'http://rd.io/x/QH6PK0JOb5s', 'http://rd.io/x/QH6PK0JTWm4', 'http://rd.io/x/QH6PK0JQDLg', 'http://rd.io/x/QH6PK0JQDVk', 'http://rd.io/x/QX-A6jdeXDK_', 'http://rd.io/x/QX-A6jdeXDVX', 'http://rd.io/x/QX-A6jd4MeY', 'http://rd.io/x/QX-A6jd0i8s', 'http://rd.io/x/QX-A6jfhnaM', 'http://rd.io/x/QX-A6jfhgn4', 'http://rd.io/x/QH6PKzlhDQ', 'http://cloudkicker.bandcamp.com/track/its-inside-me-and-im-inside-it', 'http://cloudkicker.bandcamp.com/track/let-yourself-be-huge', 'http://cloudkicker.bandcamp.com/track/oh-god', 'http://cloudkicker.bandcamp.com/track/push-it-way-up'];
